infohub/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('webhub.urls')),
    url(r'^docs/', include('rest_framework_swagger.urls')),
    url(r'^malaria/', include('malaria.urls', namespace='malaria')),
    url(r'^peacetrack/', include('peacetrack.urls')),
    url(r'^webhub/', include('webhub.urls', namespace='webhub')),
)

malaria/urls.py
from django.conf.urls import patterns, url
from malaria import views

urlpatterns = patterns(
    '',
    url(r'^create_post/$',
        views.create_post,
        name='create_post'),
    url(r'^delete_post/(?P<post_id>\d+)$',
        views.delete_post,
        name='delete_post'),
    url(r'^edit_post/(?P<post_id>\d+)$',
        views.edit_post,
        name='edit_post'),
    url(r'^list_posts/$',
        views.list_posts,
        name='list_posts'),
    url(r'^revpost/$',
        views.revpost_list,
        name='revpost_list'),
    url(r'^revpost/(?P<pk>[0-9]+)/$',
        views.revpost_detail,
        name='revpost_detail'),
    url(r'^view_post/(?P<post_id>\d+)$',
        views.view_post,
        name='view_post'),
)

webhub/urls.py
from django.conf.urls import patterns, url, include
from rest_framework import routers
from malaria import views as malaria_views
from peacetrack import views as peacetrack_views
from webhub import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'posts', malaria_views.PostViewSet)
router.register(r'revposts', malaria_views.RevPostViewSet)
router.register(r'regions', peacetrack_views.RegionViewSet)
router.register(r'sectors', peacetrack_views.SectorViewSet)
router.register(r'ptposts', peacetrack_views.PTPostViewSet)
router.register(r'projects', peacetrack_views.ProjectViewSet)
router.register(r'goals', peacetrack_views.GoalViewSet)
router.register(r'objectives', peacetrack_views.ObjectiveViewSet)
router.register(r'indicators', peacetrack_views.IndicatorViewSet)
router.register(r'outputs', peacetrack_views.OutputViewSet)
router.register(r'outcomes', peacetrack_views.OutcomeViewSet)
router.register(r'activity', peacetrack_views.ActivityViewSet)
router.register(r'measurement', peacetrack_views.MeasurementViewSet)
router.register(r'cohort', peacetrack_views.CohortViewSet)
router.register(r'volunteer', peacetrack_views.VolunteerViewSet)

urlpatterns = patterns(
    '',
    url(r'^index/$',
        views.index,
        name='index'),
    url(r'^$',
        views.dashboard,
        name='dashboard'),
    url(r'^signup_page/$',
        views.signup_page,
        name='signup_page'),
    url(r'^signup_do/$',
        views.signup_do,
        name='signup_do'),
    url(r'^send_verification_email/$',
        views.send_verification_email,
        name='send_verification_email'),
    url(r'^send_email/$',
        views.send_email,
        name='send_email'),
    url(r'^login_do/$',
        views.login_do,
        name='login_do'),
    url(r'^logout_do/$',
        views.logout_do,
        name='logout_do'),
    url(r'^profile/$',
        views.profile,
        name='profile'),
    url(r'^edit_profile/$',
        views.edit_profile,
        name='edit_profile'),
    url(r'^edit_profile_page/$',
        views.edit_profile_page,
        name='edit_profile_page'),
    url(r'^forgot_pass_page/$',
        views.forgot_pass_page,
        name='forgot_pass_page'),
    url(r'^forgot_pass/$',
        views.forgot_pass,
        name='forgot_pass'),
    url(r'^verify/$',
        views.verify,
        name='verify'),
    url(r'^reset_pass_page/$',
        views.reset_pass_page,
        name='reset_pass_page'),
    url(r'^change_pass/$',
        views.change_pass,
        name='change_pass'),
    url(r'^change_pass_page/$',
        views.change_pass_page,
        name='change_pass_page'),
    url(r'^pcuser/$',
        views.pcuser_list,
        name='pcuser_list'),
    url(r'^pcuser/(?P<pk>[0-9]+)/$',
        views.pcuser_detail,
        name='pcuser_detail'),
    url(r'^api-auth/',
        include('rest_framework.urls',
                namespace='rest_framework')),
    url(r'^api/',
        include(router.urls)),
    url(r'^aboutPC/$',
        views.aboutPC,
        name='aboutPC'),
    url(r'^policies/$',
        views.policies,
        name='policies'),
    url(r'^details/$',
        views.details,
        name='details'),
    url(r'^helpPC/$',
        views.helpPC,
        name='helpPC'),
    url(r'^testDB/$',
        views.testDB,
        name='testDB'),
)

malaria/models.py
from django.db import models
from django.core.validators import RegexValidator
from webhub.models import Pcuser


class Post(models.Model):
    # The owner of the post
    owner = models.ForeignKey(Pcuser, null=False, related_name='owner')
    title_post = models.CharField(max_length=100,
                                  validators=[
                                      RegexValidator(
                                          r'^[(A-Z)|(a-z)|(0-9)|(\s)|(\.)|(,)|(\-)|(!)|(:)]+$'
                                      )]
                                  )
    description_post = models.CharField(max_length=5000,
                                        validators=[
                                            RegexValidator(
                                                r'^[(A-Z)|(a-z)|(0-9)|(\s)|(\.)|(,)|(\-)|(!)|(:)]+$'
                                            )]
                                        )
    # link to important documents
    link_post = models.CharField(max_length=2000)
    # field to note the timestamp when the post was created
    created = models.DateTimeField(auto_now_add=True)
    # field to note the timestamp when the post was last updated
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.owner.user.username


class RevPost(models.Model):
    # The post which is being edited
    owner_rev_post = models.ForeignKey(Post,
                                       null=False,
                                       related_name='owner_rev_post')
    # The user who is editing the post
    owner_rev = models.ForeignKey(Pcuser, null=False, related_name='owner_rev')
    # revised title
    title_post_rev = models.CharField(max_length=300)
    # revised description
    description_post_rev = models.CharField(max_length=2000)
    # field to note the timestamp when the revised version was created
    created = models.DateTimeField(auto_now_add=True)
    # change in title
    title_change = models.BooleanField(default=False)
    # change in description
    description_change = models.BooleanField(default=False)

    def __unicode__(self):
        return self.owner_rev.user.username

webhub/models.py
from django.db import models
from django.contrib.auth.models import User

import os

# To update the filename of the newly uploaded photo
def update_filename(instance, filename):
    path = '/vagrant/submit/media/propics/'
    format = instance.user.username + ".jpg"
    return os.path.join(path, format)



# Django provides a table called user that stores basic user information like username, password and email id.
class Pcuser(models.Model):
    #username
    user = models.OneToOneField(User)
    #location
    location = models.CharField(max_length=300)
    #phone number
    phone = models.CharField(max_length=150)
    #gender
    gender = models.CharField(max_length=10)
    #for reset_password
    reset_pass = models.CharField(default="",max_length=320)
    
    
    #path to default user image
    image = models.CharField(max_length=300, default="http://i.imgur.com/dnjclWV.png")
    #image
    imageobj = models.ImageField(upload_to=update_filename)
    
    #verification status
    #1 - unverified
    #any other number = verification code
    verified = models.CharField(max_length=100)
    
    def __unicode__(self):
        return self.user.username

malaria/forms.py
from django.forms import ModelForm
from malaria.models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title_post', 'description_post']

webhub/forms.py
from django.forms import ModelForm
from webhub.models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title_post', 'description_post']

malaria/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from rest_framework import status
from rest_framework import viewsets
from rest_framework.decorators import api_view
from rest_framework.response import Response
from malaria.forms import PostForm
from malaria.models import Post, RevPost
from malaria.services import delete_post_by_id, get_post_by_id, get_revpost_of_owner
from webhub.checker import check
from webhub.models import Pcuser
from webhub.serializers import PostSerializer, RevPostSerializer


def list_posts(request):
    post_list = Post.objects.all()
    return render(request,
                  'malaria/list_posts.html',
                  {'post_list': post_list})


def view_post(request, post_id):

    retval = check(request)
    if retval is not None:
        return retval

    post = get_post_by_id(post_id)
    revpost = get_revpost_of_owner(post_id)
    # revpost may not exist yet so do not check it
    if post:
        return render(request,
                      'malaria/view_post.html',
                      {'post': post,
                       'revpost': revpost})
    else:
        raise Http404


def create_post(request):

    # check if the user is logged in
    retval = check(request)
    if retval is not None:
        return retval

    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.owner = request.user.pcuser
            post.save()
            return render(request,
                          'malaria/notice.html',
                          {'text': 'Post created successfully.',
                           'text1': 'Click here to view post.',
                           'post': post})
    return render(request,
                  'malaria/create_post.html',
                  {'form': form})


def edit_post(request, post_id):

    retval = check(request)
    if retval is not None:
        return retval

    post = get_post_by_id(post_id)
    if post:
        if request.method == 'POST':

            # need to get the original title_post and description_post
            # before it is changed when calling instance on PostForm
            orig_title = post.title_post
            orig_desc = post.description_post
            form = PostForm(request.POST, instance=post)

            if form.is_valid():

                owner = request.user.pcuser
                edited_title = form.cleaned_data['title_post']
                edited_desc = form.cleaned_data['description_post']

                if (orig_title != edited_title) or \
                   (orig_desc != edited_desc):

                    post = form.save(commit=False)
                    post.owner = owner
                    post.save()

                    revpost_title_change = False
                    revpost_desc_change = False

                    if(orig_title != edited_title):
                        revpost_title_change = True
                    if(orig_desc != edited_desc):
                        revpost_desc_change = True

                    revpost = RevPost(owner_rev=owner,
                                      owner_rev_post=post,
                                      title_post_rev=orig_title,
                                      description_post_rev=orig_desc,
                                      title_change=revpost_title_change,
                                      description_change=revpost_desc_change)
                    revpost.save()

                    return render(request,
                                  'malaria/notice.html',
                                  {'text': 'Post edited successfully.',
                                   'text1': 'Click here to view post.',
                                   'post': post})
                else:
                    return render(request,
                                  'malaria/notice.html',
                                  {'text': 'No changes to Post made.',
                                   'text1': 'Click here to view post.',
                                   'post': post})
            else:
                return render(request,
                              'malaria/edit_post.html',
                              {'form': form, 'post': post})
        else:
            form = PostForm(instance=post)
            return render(request,
                          'malaria/edit_post.html',
                          {'form': form, 'post': post})
    else:
        raise Http404


def delete_post(request, post_id):

    retval = check(request)
    if retval is not None:
        return retval

    if request.method == 'POST':
        if delete_post_by_id(post_id):
            return HttpResponseRedirect(reverse('malaria:list_posts'))
        else:
            raise Http404
    else:
        return render(request,
                      'malaria/delete_post.html',
                      {'post_id': post_id})


class PostViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Post endpoint that provides `list` and `detail` actions
    `list` action returns a list of all Posts
    `detail` action returns a particular Post instance based on id
    """
    queryset = Post.objects.all()
    serializer_class = PostSerializer


@api_view(['GET', 'POST'])
def revpost_list(request):
    if request.method == 'GET':
        revpost = RevPost.objects.all()
        serializer = RevPostSerializer(revpost, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        serializer = RevPostSerializer(data=request.DATA)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'PUT', 'DELETE'])
def revpost_detail(request, pk):
    try:
        revpost = RevPost.objects.get(pk=pk)
    except Pcuser.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        # to do: the post below is undefined, fix it
        serializer = RevPostSerializer(post)
        return Response(serializer.data)

    elif request.method == 'PUT':
        serializer = RevPostSerializer(post, data=request.DATA)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        revpost.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class RevPostViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = RevPost.objects.all()
    serializer_class = RevPostSerializer

webhub/templates/webhub/create_post.html
{% extends "infohub/base.html" %}

{% block content %}
<head>
    <title>Add New Post</title>
</head>
<body>
    <br><br><br><br><br><br>
    <center><h2><font color="#2c0f00"> Malaria : infoHub</font> </h2></center>
    <div style="width:600px; height:400px; margin:0 auto; background-color:#0d8b97;">
    <br>
    <center><b><h3><font color="white">New Post</font></h3></b></center>
    <br>
    <form action="{% url 'webhub:create_post' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-1">
            </div>
            <div class="col-md-5">
                <p><font color="white"><h4>Title</h4></font></p>
            </div>
            <div class="col-md-6">
                <input type="text" name="title_post" value="{% if form.title_post.value %}{{ form.title_post.value }}{% endif %}">
                {% if form.title_post.errors %}
                    <p>
                        <strong>
                            {% for error in form.title_post.errors %}
                                {{ error }}
                            {% endfor %}
                        </strong>
                    </p>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-1">
            </div>
            <div class="col-md-5">
                <p><font color="white"><h4>Description</h4></font></p>
            </div>
            <div class="col-md-6">
                <textarea rows="5" name="description_post">{% if form.description_post.value %}{{ form.description_post.value }}{% endif %}</textarea>
                {% if form.description_post.errors %}
                    <p>
                        <strong>
                            {% for error in form.description_post.errors %}
                                {{ error }}
                            {% endfor %}
                        </strong>
                    </p>
                {% endif %}
            </div>
        </div>
        <br>
        <br><center>
        <div class="row">
            <div class="col-md-3">
            </div>
            <div class="col-md-3">
                <button type="submit" class="btn btn-default">Submit</button>
            </div>
            <div class="col-md-3">
                <a href="{% url 'webhub:malaria' %}" class="btn btn-default">Cancel</a>
            </div>
            <div class="col-md-3">
            </div>
        </div>
    </form>
    <br>    
    </div>
    <br><br><br>
</body>
{% endblock %}

webhub/templates/webhub/delete_post.html
{% extends "infohub/base.html" %}

{% block content %}
    <head>
        <title>Delete Post</title>
    </head>
    <body>
        <br><br><br><br><br><br>
        <center>
            <h2>
                <font color="#2c0f00">Malaria : infoHub</font>
            </h2>
        </center>
        <div style="width:600px; height:200px; margin:0 auto; background-color:#0d8b97;">
            <br>
            <center>
                <b>
                    <h3>
                        <font color="white">Delete Post</font>
                    </h3>
                </b>
            </center>
            <br>
            <form action="{% url 'webhub:delete_post' post_id %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label class="col-sm-offset-2">Are you sure you want to delete this Post?</label>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2">
                        <button type="submit" class="btn btn-default">Yes, delete this Post</button>
                        <a href="{% url 'webhub:malaria' %}" class="btn btn-default">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
        <br><br><br><br>
    </body>
{% endblock %}

webhub/templates/webhub/edit_post.html
{% extends "infohub/base.html" %}

{% block content %}
<head>
    <title>Edit Post</title>
</head>
<body>
    <br><br><br><br><br><br>
    <center><h2><font color="#2c0f00"> Malaria : infoHub</font> </h2></center>
    <div style="width:600px; height:auto; margin:0 auto; padding-bottom:10px; background-color:#0d8b97;">
        <br>
        <center><b><h3><font color="white">Edit Post</font></h3></b></center>
        <br>
        <form action="{% url 'webhub:edit_post' post.id %}" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-1">
                </div>
                <div class="col-md-5">
                    <p><font color="white"><h4>Title</h4></font></p>
                </div>
                <div class="col-md-6">
                    <input type="text" name="title_post" value="{% if form.title_post.value %}{{ form.title_post.value }}{% endif %}">
                    {% if form.title_post.errors %}
                        <p>
                            <strong>
                                {% for error in form.title_post.errors %}
                                    {{ error }}
                                {% endfor %}
                            </strong>
                        </p>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-1">
                </div>
                <div class="col-md-5">
                    <p><font color="white"><h4>Description</h4></font></p>
                </div>
                <div class="col-md-6">
                    <textarea rows="5" name="description_post">{% if form.title_post.value %}{{ form.description_post.value }}{% endif %}</textarea>
                    {% if form.description_post.errors %}
                        <p>
                            <strong>
                                {% for error in form.description_post.errors %}
                                    {{ error }}
                                {% endfor %}
                            </strong>
                        </p>
                    {% endif %}
                </div>
            </div>
            <br><center>
            <div class="row">
                <div class="col-md-3">
                </div>
                <div class="col-md-3">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
                <div class="col-md-3">
                    <a href="{% url 'webhub:malaria' %}" class="btn btn-default">Cancel</a>
                </div>
                <div class="col-md-3">
                </div>
            </div>
        </form>
        <br>    
    </div>
    <br><br>
</body>
{% endblock %}

webhub/templates/webhub/malaria.html
{% extends "infohub/base.html" %}

{% block content %}
<head>
    <title>Malaria | infoHub</title>
</head>
<body>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <center>
        <h2>
            <font color="#2c0f00"> Malaria : infoHub</font>
        </h2>
    </center>
    <div style="width:600px; height:auto; margin:0 auto; background-color:#0d8b97; padding-right:15px; padding-left:15px;">
        <br>
        <br>
        <a href="{% url 'webhub:create_post' %}" class="btn btn-default" style="float:right;">New Post</a>
        {% if post_list %}
            <table class="table">
            <thead>
                <tr>
                    <th>
                        <font color="white">
                            <h3>Post</h3>
                        </font>
                    </th>
                    <th>
                        <font color="white">
                            <h3>Action</h3>
                        </font>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for post in post_list %}
                    <tr>
                        <td>
                            <a href="{% url 'webhub:view_post' post.id %}"><font color="white">{{ post.title_post }}</font></a>
                        </td>
                        <td>
                            <a href="{% url 'webhub:edit_post' post.id %}" class="btn btn-default">Edit</a>
                            <a href="{% url 'webhub:delete_post' post.id %}" class="btn btn-default">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            </table>
        {% else %}
            <center><font color="white"><h4>There are No Posts right now.</h4></font><br><br><br><br><br><br><br><br><br><br></center>
        {% endif %}
        </div>
    </div>
    <br>
    <br>
</body>
{% endblock %}

webhub/templates/webhub/new_post.html
{% extends "infohub/base.html" %}

{% block content %}
<head>
    <title>Add New Post</title>
</head>
<body>
    <br><br><br><br><br><br>
    <center><h2><font color="#2c0f00"> Malaria : infoHub</font> </h2></center>
    <div style="width:600px; height:400px; margin:0 auto; background-color:#0d8b97;">
    <br>
    <center><b><h3><font color="white">New Post</font></h3></b></center>
    <br>
    <form action="/post_new/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-1">
            </div>
            <div class="col-md-5">
                <p><font color="white"><h4>Title</h4></font></p>
            </div>
            <div class="col-md-6">
                <input type="text" name="title_post">
                {% if form.title_post.errors %}
                    <p>
                        <strong>
                            {% for error in form.title_post.errors %}
                                {{ error }}
                            {% endfor %}
                        </strong>
                    </p>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-1">
            </div>
            <div class="col-md-5">
                <p><font color="white"><h4>Description</h4></font></p>
            </div>
            <div class="col-md-6">
                <textarea name="description_post" rows="5"></textarea>
                {% if form.description_post.errors %}
                    <p>
                        <strong>
                            {% for error in form.description_post.errors %}
                                {{ error }}
                            {% endfor %}
                        </strong>
                    </p>
                {% endif %}
            </div>
        </div>
        <br>
        <br><center>
        <div class="row">
            <div class="col-md-3">
            </div>
            <div class="col-md-3">
                <input type="submit" name="submit" value="SUBMIT" class="btn">
            </div>
            <div class="col-md-3">
                <button class="btn"><a href="#"><font color="black">CANCEL</font></a></center></button>
            </div>
            <div class="col-md-3">
            </div>
        </div>
    </form>
    <br>    
    </div>
    <br><br><br>
</body>
{% endblock %}

webhub/templates/webhub/notice.html
{% extends "infohub/base.html" %}

{% block content %}
    <head>
        <title>Notice</title>
    </head>
    <body>
        <br><br><br><br><br><br><br><br>
        <center><p><h4> {{ text }} </h4></p></center>
        <center><p><h4><a href="{% url 'webhub:view_post' post.id %}"><u> {{ text1 }} </u></a></h4></p></center>
        <br><br><br><br><br><br><br><br><br><br><br><br><br>
    </body>
{% endblock %}

webhub/templates/webhub/view_post.html
{% extends "infohub/base.html" %}    

{% block content %}
<head>
    <title>Post | {{ post.title_post }}</title>
</head>
<body>
    <br><br><br><br><br><br>
    <center><h2><font color="#2c0f00"> Malaria : infoHub</font></h2></center>
    <div style="width:600px; height:auto; margin:0 auto; background-color:#0d8b97;">
        <br>
        <center><b><h3><font color="white">View Post</font></h3></b></center>
        <br>
        <div class="row">
            <div class="col-md-1">
            </div>
            <div class="col-md-5">
                <p><font color="white"><h4>Title : </h4></font></p>
            </div>
            <div class="col-md-6">
                <p><font color="white"><h4>{{ post.title_post }}</h4></font></p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-1">
            </div>
            <div class="col-md-5">
                <p><font color="white"><h4>Description : </h4></font></p>
            </div>
            <div class="col-md-6">
                <p><font color="white"><h4>{{ post.description_post }}</h4></font></p>
            </div>
        </div><br>
        <br>    
        <center>
            <a href="{% url 'webhub:edit_post' post.id %}" class="btn btn-default">Edit</a>
            <a href="{% url 'webhub:delete_post' post.id %}" class="btn btn-default">Delete</a>
        </center>
        <br>
    </div>
    <br>
    <div style="width:600px; height:auto; margin:0 auto; background-color:#0d8b97;"><br>
        <center><b><h4><font color="white"><u>Revision History of this Post</u></font></h4></b></center><br>
        <div class="row">
            <div class="col-md-1">
            </div>
            <div class="col-md-10">    
                <h5><font color="white">The post was created by <a href="/profile/?id={{post.owner.id}}"><font color="white"><b><u>{{ post.owner }}</u></b></font></a> on {{ post.created }}</font></h5>
                {% for rev in revpost %}
                    <li style="color:white"><h5><font color="white"><b>The post was updated by <a href="/profile/?id={{rev.owner_rev.user.id}}"><font color="white"><b><u>{{ rev.owner_rev.user.first_name }}</b></u></font></a> on {{ rev.created }}</b></font></h5></li>
                    <h5><font color="#e2d7bb">
                    {% if rev.title_change %}
                        The title has been changed from "{{ rev.title_post_rev }}" to "{{ post.title_post }}"
                    {% endif %}
                    {% if rev.description_change %}
                        The description has been changed from "{{ rev.description_post_rev }}" to "{{ post.description_post }}"
                    {% endif %}
                    </font></h5>    
                {% endfor %}
            </div>
            <div class="col-md-1">
            </div>
        </div>
    </div>
    <br><br>
</body>
{% endblock %}